##
# Default funding configuration for GitHub.
#
# @link https://github.com/sponsors/andrewvaughan
# @link https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/about-github-sponsors
#
---
github:
  - andrewvaughan

custom: https://andrewvaughan.github.io/sponsorships
