# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: true
IGNORE_GITIGNORED_FILES: true
LINTER_RULES_PATH: .config/linters
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: true

DISABLE_LINTERS:
  # Lychee is _extremely_ slow right now - consider the usefulness of dead hyper link checking before re-enabling
  - SPELL_LYCHEE

REPOSITORY_KICS_CONFIG_FILE: kics.yml

MAKEFILE_CHECKMAKE_FILE_EXTENSIONS:
  - .mak
