##
# Global Makefile
#
# Do not edit this file directly. Please refer to the `.config/make` directory for managing, adding, or removing
# targets. File order matters for Make, so it is important that all files in this directory are appropriately named, as
# they will be loaded in alphabetical-order.
#

-include $(addsuffix /*.mak, $(shell find .config/make -type d))
