##
# Bug request GitHub Issue form configuration.
#
# @link https://ajv.to/github-pr-template
#
---
name: Bug report

description: Report a discovered bug in the project.

labels:
  - "Needs Triage"
  - "Request: Bug Fix"

assignees:
  - andrewvaughan

body:
  - type: markdown
    attributes:
      value: >-
        Thank you for taking the time to contribute a bug report to this project. Please aim to be as detailed as
        possible when detailing the sections below, as that helps Project Maintainers replicate and, with your help,
        address any bugs found.

        > **If you believe this is a Security Issue**, please draft a
        > [Security Advisory Report](https://github.com/andrewvaughan/template-core/security/advisories/new) instead.

  ## -------------------------------------------------------------------------------------------------------------------
  # Environment.
  #

  - type: markdown
    attributes:
      value: >-
        ---

        ## Environment details

        Before gathering details on the Issue itself, it's important to understand more about your environment and the
        state of your machine when the bug occurred:

  ##
  # Project version.
  #
  - type: dropdown
    id: version
    attributes:
      label: Project versions
      description: What versions of this project does this occur with that you are aware of?
      multiple: true
      options:
        - v0.0.0
    validations:
      required: true

  ##
  # Scope.
  #
  - type: dropdown
    id: scope
    attributes:
      label: Scopes
      description: What components within the project does this pertain to, if known?
      multiple: true
      options:
        - Full Project
        - Other

  ##
  # Operating system.
  #
  - type: dropdown
    id: operating_system
    attributes:
      label: Operating systems
      description: What operating systems has this occurred on that you are aware of?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux/Unix
        - iOS
        - Android
        - Other
    validations:
      required: true

  ##
  # Operating system version.
  #
  - type: input
    id: operating_system_version
    attributes:
      label: Operating system versions
      description: What versions of the operating systems in the preceding question are you using?
      placeholder: "Example: 8.1, 11, Ventura 13.5.2"
    validations:
      required: true

  ##
  # Browser.
  #
  - type: dropdown
    id: browser
    attributes:
      label: Browsers
      description: What browsers has this occurred on?
      multiple: true
      options:
        - Chrome
        - Chrome for Android
        - Chrome for iOS
        - Edge
        - Firefox
        - Firefox for Android
        - Firefox for iOS
        - Opera
        - Safari
        - Safari for iOS
        - Other

  ##
  # Browser version.
  #
  - type: input
    id: browser_version
    attributes:
      label: Browser versions
      description: What versions of the browsers in the preceding question were you using?
      placeholder: "Example: Version 117.0.5938.92 (Official Build) (arm64)"

  ## -------------------------------------------------------------------------------------------------------------------
  # Colloquy.
  #

  - type: markdown
    attributes:
      value: >-
        ---

        ## Colloquy

        In order to understand the unexpected behavior better, please provide as much detail as possible for these
        questions:

  ##
  # Expected results.
  #
  - type: textarea
    id: expected_results
    attributes:
      label: What did you expect to happen?
      description: Describe what the expected behavior was that didn't occur.
    validations:
      required: true

  ##
  # Actual results.
  #
  - type: textarea
    id: actual_results
    attributes:
      label: What actually happened?
      description: Describe what the actual behavior was that didn't match the preceding expectation.
    validations:
      required: true

  ##
  # Steps to reproduce.
  #
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Please describe, in detail, what steps you took and how another person can reproduce the problem.
      placeholder: |-
        1.
        2.
        3.
        ...
    validations:
      required: true

  ##
  # Consistency.
  #
  - type: dropdown
    id: consistency
    attributes:
      label: How consistent is this bug?
      description: Is this something that always happens, or comes and goes?
      options:
        - Constant
        - On and off
        - Once or twice
        - Other
      default: 0
    validations:
      required: true

  ## -------------------------------------------------------------------------------------------------------------------
  # Dumps.
  #

  - type: markdown
    attributes:
      value: >-
        ---

        ## Additional data

        Any information from your environment that could help debug this bug would be extremely helpful. Please provide
        screenshots, logs, configuration settings, or anything else that might be of use in enabling the Project
        Maintainers to replicate this bug.

  ##
  # Configuration Settings.
  #
  - type: textarea
    id: configuration_settings
    attributes:
      label: Configuration settings
      description: >-
        Please paste your configuration file. Remember to review for sensitive data before submitting.
      render: YAML

  ##
  # Screenshots.
  #
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: >-
        If applicable, please use the provided image upload tool in the text editor below to provide any screenshots
        that may be helpful in illustrating this bug.
      placeholder: |
        ![Example Screenshot Title](https://imgur.com/gallery/0DQQTAv/)

  ##
  # Logs.
  #
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please turn on verbose debugging via the command options (`-vv`) and paste your log output here.
      render: Shell

  ## -------------------------------------------------------------------------------------------------------------------
  # Subjective.
  #

  - type: markdown
    attributes:
      value: >-
        ---

        ## Conclusion

        Your expertise is extremely valuable in determining the appropriate course of action for this Issue. Any
        additional information you might provide helps to determine the prioritization and execution of this effort.

  ##
  # Priority.
  #
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: In your opinion, how important is this Issue?
      options:
        - Critical (project fails without it)
        - Important (significantly improves the project)
        - Moderate (similar to work prioritized currently)
        - Low (not urgent)
        - Trivial (nice to have)

  ##
  # Additional context.
  #
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: >-
        If there is anything else the Project Maintainers should know that helps explain or prioritize this Issue,
        please provide that additional information, here.

  ## -------------------------------------------------------------------------------------------------------------------
  # Terms of service.
  #

  ##
  # Code of Conduct.
  #
  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: >-
        By submitting this Issue, I agree to the terms within and agree to follow this project's
        [Code of Conduct](https://github.com/andrewvaughan/template-core?tab=coc-ov-file#readme).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
