##
# Documentation update GitHub Issue form configuration.
#
# @link https://t.ly/-Gbqv
#
---
name: Documentation request

description: Request updated or new documentation.

labels:
  - "Needs Triage"
  - "Request: Documentation"

assignees:
  - andrewvaughan

body:
  - type: markdown
    attributes:
      value: >-
        Thank you for taking the time to recommend a documentation improvement. The goals of this project are to be as
        approachable and efficient for developers and users as possible, and proper documentation is a major part of
        that strategy.

  ##
  # Scope.
  #
  - type: dropdown
    id: scope
    attributes:
      label: Scopes
      description: What components within the project does this pertain to, if known?
      multiple: true
      options:
        - Full Project
        - Other

  ##
  # New or update.
  #
  - type: dropdown
    id: update_target
    attributes:
      label: New or existing documentation
      description: Is this new documentation or an update to existing documentation?
      options:
        - New documentation
        - Existing documentation
      default: 1
    validations:
      required: true

  ##
  # Description.
  #
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the documentation need, in detail.
    validations:
      required: true

  ##
  # Examples.
  #
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: >-
        If you have any examples of this documentation, or can provide your own example of how the documentation might
        look, please provide it here.

  ## -------------------------------------------------------------------------------------------------------------------
  # Subjective.
  #

  - type: markdown
    attributes:
      value: >-
        ---

        ## Conclusion

        Your expertise is extremely valuable in determining the appropriate course of action for this Issue. Any
        additional information you might provide helps to determine the prioritization and execution of this effort.

  ##
  # Priority.
  #
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: In your opinion, how important is this Issue?
      options:
        - Critical (project fails without it)
        - Important (significantly improve the project)
        - Moderate (similar to most work being done today)
        - Low (clear value, but in no way urgent)
        - Trivial (nice to have)

  ##
  # Additional context.
  #
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: >-
        If there is anything else the Project Maintainers should know that helps explain or prioritize this Issue,
        please provide that additional information, here.

  ## -------------------------------------------------------------------------------------------------------------------
  # Terms of service.
  #

  ##
  # Code of Conduct.
  #
  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: >-
        By submitting this Issue, I agree to the terms within and agree to follow this project's
        [Code of Conduct](https://github.com/andrewvaughan/template-core?tab=coc-ov-file#readme).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
