##
# Feature request GitHub Issue form configuration.
#
# @link https://t.ly/-Gbqv
#
---
name: Feature request

description: Request a feature or submit an idea for development.

labels:
  - "Needs Triage"
  - "Request: Feature Request"

assignees:
  - andrewvaughan

body:
  - type: markdown
    attributes:
      value: >-
        Thank you for taking the time to recommend a feature or submit an idea. Before submitting, please take a moment
        to review the standards on what feature requests Project Maintainers accept in the project's
        [Contributing Guidelines](/andrewvaughan/template-core/blob/main/.github/CONTRIBUTING.md#submit-an-idea).

  ##
  # Scope.
  #
  - type: dropdown
    id: scope
    attributes:
      label: Scopes
      description: What components within the project does this pertain to?
      multiple: true
      options:
        - Everything
        - Other
      default: 0

  ##
  # Problem.
  #
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve or opportunity do you see that exists for this idea or feature?
    validations:
      required: true

  ##
  # Benefits.
  #
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefit does this change bring to the project and community?

  ##
  # Recommended approach.
  #
  - type: textarea
    id: approach
    attributes:
      label: Recommended approach
      description: >-
        If known, what approach do you recommend to the problem or opportunity? Please include any diagrams, mockups, or
        illustrations in this area, if they might help explain your idea, by using the image upload tool in the text
        editor.

  ##
  # Examples.
  #
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: >-
        If you have any examples of other projects or utilities, or can provide your own example as to how this might
        function, please provide it here.

  ## -------------------------------------------------------------------------------------------------------------------
  # Subjective.
  #

  - type: markdown
    attributes:
      value: >-
        ---

        ## Conclusion

        Your expertise is extremely valuable in determining the appropriate course of action for this Issue. Any
        additional information you might provide helps to determine the prioritization and execution of this effort.

  ##
  # Priority.
  #
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: In your opinion, how important is this Issue?
      options:
        - Critical (project fails without it)
        - Important (significantly improves the project)
        - Moderate (similar to work prioritized currently)
        - Low (not urgent)
        - Trivial (nice to have)

  ##
  # Additional context.
  #
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: >-
        If there is anything else the Project Maintainers should know that helps explain or prioritize this Issue,
        please provide that additional information, here.

  ## -------------------------------------------------------------------------------------------------------------------
  # Terms of service.
  #

  ##
  # Code of Conduct.
  #
  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: >-
        By submitting this Issue, I agree to the terms within and agree to follow this project's
        [Code of Conduct](https://github.com/andrewvaughan/template-core?tab=coc-ov-file#readme).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
