##
# Operational change request GitHub Issue form configuration.
#
# @link https://t.ly/-Gbqv
#
---
name: Operational request

description: Request updates to automation, integrations, or other operational efforts.

labels:
  - "Needs Triage"
  - "Request: Ops"

assignees:
  - andrewvaughan

body:
  - type: markdown
    attributes:
      value: >-
        Thank you for taking the time to recommend an operational improvement. The goals of this project are to be as
        approachable and efficient for developers and users as possible, so creating an effective and automated
        integration lifecycle is critical to maintaining rapid development.

  ##
  # Description.
  #
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the operational change or addition needed, in detail.
    validations:
      required: true

  ##
  # Examples.
  #
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: >-
        If you have any examples of this request in action, or can provide your own example of how this might function,
        please provide it here.

  ## -------------------------------------------------------------------------------------------------------------------
  # Subjective.
  #

  - type: markdown
    attributes:
      value: >-
        ---

        ## Conclusion

        Your expertise is extremely valuable in determining the appropriate course of action for this Issue. Any
        additional information you might provide helps to determine the prioritization and execution of this effort.

  ##
  # Priority.
  #
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: In your opinion, how important is this Issue?
      options:
        - Critical (project fails without it)
        - Important (significantly improves the project)
        - Moderate (similar to work prioritized currently)
        - Low (not urgent)
        - Trivial (nice to have)

  ##
  # Additional context.
  #
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: >-
        If there is anything else the Project Maintainers should know that helps explain or prioritize this Issue,
        please provide that additional information, here.

  ## -------------------------------------------------------------------------------------------------------------------
  # Terms of service.
  #

  ##
  # Code of Conduct.
  #
  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: >-
        By submitting this Issue, I agree to the terms within and agree to follow this project's
        [Code of Conduct](https://github.com/andrewvaughan/template-core?tab=coc-ov-file#readme).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
