##
# Operational change request form GitHub issue template
#
# @link https://t.ly/-Gbqv

name: Operational Request

description: Request updates to automation, integrations, or other operational efforts.

labels:
  - "Needs Triage"
  - "Request: Ops"

assignees:
  - andrewvaughan

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to bring an operational need to our attention. Creating a smooth development
        lifecycle is critical to maintaining the community, and all ideas are welcome.

  # Description
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the operational change or addition needed, in detail.
    validations:
      required: true

  # Priority
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: In your opinion, how important is it that this operational need be resolved?
      options:
        - Critical - the project fails without it
        - Important - will significantly improve the user experience
        - Moderate - this is on par with other, existing elements of the roadmap
        - Low - this adds clear value, but it is in no way urgent
        - Trivial - this is a nice to have
      default: 2
    validations:
      required: true

  # Examples
  - type: textarea
    id: examples
    attributes:
      label: Example(s)
      description: |
        If you have any examples of this request in action, or can provide your own example of how this might function,
        please provide it here.

  # Additional Context
  - type: textarea
    id: other-context
    attributes:
      label: Additional Context
      description: |
        If there is anything else the project maintainers should know that will help with this issue, please provide
        additional information, here. This entry will be
        [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) rendered.
      render: Markdown

  ## TERMS -------------------------------------------------------------------------------------------------------------

  # Code of Conduct
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, I agree to the terms within and will follow this project's
        [Code of Conduct](https://github.com/andrewvaughan/template-core?tab=coc-ov-file#readme)
      options:
        - label: I agree to follow this project's Code of Conduct
