##
# Makefile dictionary for CSpell
#
# @link https://github.com/streetsidesoftware/cspell-dicts/issues/2665
# @link https://github.com/streetsidesoftware/vscode-spell-checker/issues/2883
#

MAKEFLAGS
ONESHELL
SHELLFLAGS

endef
ifdef
ifeq
ifneq
findstring
